name: Docker Publish

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine changed files
        id: changes
        run: |
          echo "magic_mirror=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^magic-mirror/' | wc -l)" >> $GITHUB_ENV
          echo "llm=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^llm-web-backend/' | wc -l)" >> $GITHUB_ENV
          echo "nfs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^nfs/' | wc -l)" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image for magic mirror
        if: env.magic_mirror != '0'
        uses: docker/build-push-action@v4
        with:
          context: ./magic-mirror
          file: ./magic-mirror/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/containers/magic-mirror:latest
          platforms: linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for llm
        if: env.llm != '0'
        uses: docker/build-push-action@v4
        with:
          context: ./llm-web-backend
          file: ./llm-web-backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/containers/llm-web-backend:latest
          platforms: linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for nfs
        if: env.nfs != '0'
        uses: docker/build-push-action@v4
        with:
          context: ./nfs
          file: ./nfs/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/containers/nfs:latest
          platforms: linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max