name: Docker Publish

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image for magic mirror
        uses: docker/build-push-action@v4
        with:
          context: ./magic-mirror
          file: ./magic-mirror/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/containers/magic-mirror:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8

      - name: Build and push Docker image for llm
        uses: docker/build-push-action@v4
        with:
          context: ./llm-web-backend
          file: ./llm-web-backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/containers/llm-web-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8
